services:
  scraper:
    build: .
    container_name: scraper_service
    environment:
      DB_HOST: aws-1-eu-west-1.pooler.supabase.com
      DB_PORT: 6543
      DB_NAME: postgres
      DB_USER: postgres.oahyvwctxtyyyjrrcezz
      DB_PASSWORD: MKdons8888****xl
    extra_hosts:
      - "host.docker.internal:host-gateway"
